import NewsModel from "../../../utils/news/newsModel.js";

export const Mariupol = NewsModel("mariupols");
export const Kramatorsk = NewsModel("kramatorsks");
export const Slovyansk = NewsModel("slovyansks");
export const Yenakievo = NewsModel("yenakievos");
export const Kostyantynivka = NewsModel("kostyantynivkas");
export const Pokrovsk = NewsModel("pokrovsks");
export const Drushkivka = NewsModel("drushkivkas");
export const Hartsyzsk = NewsModel("hartsyzsks");
export const Shakhtarsk = NewsModel("shakhtarsks");
export const Snishne = NewsModel("snishnes");
export const Myrnohrad = NewsModel("myrnohrads");
export const Dobropillia = NewsModel("dobropillias");
export const Donetsk = NewsModel("donetsks");
export const Makiivka = NewsModel("makiivkas");
export const Gorlivka = NewsModel("gorlivkas");
export const Toretsk = NewsModel("toretsks");
export const Avdiyivka = NewsModel("avdiyivkas");
export const Liman = NewsModel("limans");
export const Selidove = NewsModel("selidoves");
export const Volnovakha = NewsModel("volnovakhas");
export const Dokuchaevsk = NewsModel("dokuchaevsks");
export const Amvrosiivka = NewsModel("amvrosiivkas");
export const Kurakhove = NewsModel("kurakhoves");
export const Bahmut = NewsModel("bahmuts");
