import NewsController from "../../controllers/newsController.js"
import { Router } from 'express'

const router = Router()

router.get('/berezan/news', NewsController.getAllBerezanNews)
router.get('/berezan/news/:id', NewsController.getBerezanNewsById)
router.get('/bilacerkva/news', NewsController.getAllBilacerkvaNews)
router.get('/bilacerkva/news/:id', NewsController.getBilacerkvaNewsById)
router.get('/boryspil/news', NewsController.getAllBoryspilNews)
router.get('/boryspil/news/:id', NewsController.getBoryspilNewsById)
router.get('/boyarka/news', NewsController.getAllBoyarkaNews)
router.get('/boyarka/news/:id', NewsController.getBoyarkaNewsById)
router.get('/brovary/news', NewsController.getAllBrovaryNews)
router.get('/brovary/news/:id', NewsController.getBrovaryNewsById)
router.get('/bucha/news', NewsController.getAllBuchaNews)
router.get('/bucha/news/:id', NewsController.getBuchaNewsById)
router.get('/fastiv/news', NewsController.getAllFastivNews)
router.get('/fastiv/news/:id', NewsController.getFastivNewsById)
router.get('/irpin/news', NewsController.getAllIrpinNews)
router.get('/irpin/news/:id', NewsController.getIrpinNewsById)
router.get('/kyiv/news', NewsController.getAllKyivNews)
router.get('/kyiv/news/:id', NewsController.getKyivNewsById)
router.get('/obukhiv/news', NewsController.getAllObukhivNews)
router.get('/obukhiv/news/:id', NewsController.getObukhivNewsById)
router.get('/pereyaslav/news', NewsController.getAllPereyaslavNews)
router.get('/pereyaslav/news/:id', NewsController.getPereyaslavNewsById)
router.get('/skvyra/news', NewsController.getAllSkvyraNews)
router.get('/skvyra/news/:id', NewsController.getSkvyraNewsById)
router.get('/slavutych/news', NewsController.getAllSlavutychNews)
router.get('/slavutych/news/:id', NewsController.getSlavutychNewsById)
router.get('/vasylkiv/news', NewsController.getAllVasylkivNews)
router.get('/vasylkiv/news/:id', NewsController.getVasylkivNewsById)
router.get('/vyshhorod/news', NewsController.getAllVyshhorodNews)
router.get('/vyshhorod/news/:id', NewsController.getVyshhorodNewsById)
router.get('/vyshneve/news', NewsController.getAllVyshneveNews)
router.get('/vyshneve/news/:id', NewsController.getVyshneveNewsById)
router.get('/yagotyn/news', NewsController.getAllYagotynNews)
router.get('/yagotyn/news/:id', NewsController.getYagotynNewsById)

export default router