import { Router } from "express";
import DonetskDeleteNewsController from "../../controllers/regionNews/Donetsk/DonetskDeleteNewsController.js";
import DonetskGetAllNewsController from "../../controllers/regionNews/Donetsk/DonetskGetAllNewsController.js";
import DonetskGetAllNewsWithNNController from "../../controllers/regionNews/Donetsk/DonetskGetAllNewsWithNNController.js";
import DonetskGetNewsByDateController from "../../controllers/regionNews/Donetsk/DonetskGetNewsByDateController.js";
import DonetskGetNewsByIdOrUrlController from "../../controllers/regionNews/Donetsk/DonetskGetNewsByIdOrUrlController.js";
import DonetskSearchNewsController from "../../controllers/regionNews/Donetsk/DonetskSearchNewsController.js";
import DonetskUpdateNewsController from "../../controllers/regionNews/Donetsk/DonetskUpdateNewsController.js";
import { checkAuth } from "../../middleware/checkAuth.js";

const router = Router();

// GetAllNews
router.get("/amvrosiivka/news"),
  DonetskGetAllNewsController.getAllAmvrosiivkaNews;
router.get("/avdiyivka/news", DonetskGetAllNewsController.getAllAvdiyivkaNews);
router.get("/bahmut/news", DonetskGetAllNewsController.getAllBahmutNews);
router.get(
  "/dobropilla/news",
  DonetskGetAllNewsController.getAllDobropilliaNews
);
router.get(
  "/dokuchaevsk/news",
  DonetskGetAllNewsController.getAllDokuchaevskNews
);
router.get("/donetsk/news", DonetskGetAllNewsController.getAllDonetskNews);
router.get(
  "/druzhkivka/news",
  DonetskGetAllNewsController.getAllDrushkivkaNews
);
router.get("/gorlivka/news", DonetskGetAllNewsController.getAllGorlivkaNews);
router.get("/hartsyzk/news", DonetskGetAllNewsController.getAllHartsyzskNews);
router.get(
  "/kostyantynivka/news",
  DonetskGetAllNewsController.getAllKostyantynivkaNews
);
router.get(
  "/kramatorsk/news",
  DonetskGetAllNewsController.getAllKramatorskNews
);
router.get("/kurakhove/news", DonetskGetAllNewsController.getAllKurakhoveNews);
router.get("/liman/news", DonetskGetAllNewsController.getAllLimanNews);
router.get("/makiivka/news", DonetskGetAllNewsController.getAllMakiivkaNews);
router.get("/mariupol/news", DonetskGetAllNewsController.getAllMariupolNews);
router.get("/myrnograd/news", DonetskGetAllNewsController.getAllMyrnohradNews);
router.get("/pokrovsk/news", DonetskGetAllNewsController.getAllPokrovskNews);
router.get("/selidove/news", DonetskGetAllNewsController.getAllSelidoveNews);
router.get(
  "/shakhtarsk/news",
  DonetskGetAllNewsController.getAllShakhtarskNews
);
router.get("/slavyansk/news", DonetskGetAllNewsController.getAllSlovyanskNews);
router.get("/snishne/news", DonetskGetAllNewsController.getAllSnishneNews);
router.get("/toretsk/news", DonetskGetAllNewsController.getAllToretskNews);
router.get("/volnovaha/news", DonetskGetAllNewsController.getAllVolnovakhaNews);
router.get("/yenakievo/news", DonetskGetAllNewsController.getAllYenakievoNews);

// Get All News With NN
router.get(
  "/amvrosiivka/with-nn",
  DonetskGetAllNewsWithNNController.getAllAmvrosiivkaNews
);
router.get(
  "/avdiyivka/with-nn",
  DonetskGetAllNewsWithNNController.getAllAvdiyivkaNews
);
router.get(
  "/bahmut/with-nn",
  DonetskGetAllNewsWithNNController.getAllBahmutNews
);
router.get(
  "/dobropilla/with-nn",
  DonetskGetAllNewsWithNNController.getAllDobropilliaNews
);
router.get(
  "/dokuchaevsk/with-nn",
  DonetskGetAllNewsWithNNController.getAllDokuchaevskNews
);
router.get(
  "/donetsk/with-nn",
  DonetskGetAllNewsWithNNController.getAllDonetskNews
);
router.get(
  "/druzhkivka/with-nn",
  DonetskGetAllNewsWithNNController.getAllDrushkivkaNews
);
router.get(
  "/gorlivka/with-nn",
  DonetskGetAllNewsWithNNController.getAllGorlivkaNews
);
router.get(
  "/hartsyzk/with-nn",
  DonetskGetAllNewsWithNNController.getAllHartsyzskNews
);
router.get(
  "/kostyantynivka/with-nn",
  DonetskGetAllNewsWithNNController.getAllKostyantynivkaNews
);
router.get(
  "/kramatorsk/with-nn",
  DonetskGetAllNewsWithNNController.getAllKramatorskNews
);
router.get(
  "/kurakhove/with-nn",
  DonetskGetAllNewsWithNNController.getAllKurakhoveNews
);
router.get("/liman/with-nn", DonetskGetAllNewsWithNNController.getAllLimanNews);
router.get(
  "/makiivka/with-nn",
  DonetskGetAllNewsWithNNController.getAllMakiivkaNews
);
router.get(
  "/mariupol/with-nn",
  DonetskGetAllNewsWithNNController.getAllMariupolNews
);
router.get(
  "/myrnograd/with-nn",
  DonetskGetAllNewsWithNNController.getAllMyrnohradNews
);
router.get(
  "/pokrovsk/with-nn",
  DonetskGetAllNewsWithNNController.getAllPokrovskNews
);
router.get(
  "/selidove/with-nn",
  DonetskGetAllNewsWithNNController.getAllSelidoveNews
);
router.get(
  "/shakhtarsk/with-nn",
  DonetskGetAllNewsWithNNController.getAllShakhtarskNews
);
router.get(
  "/slavyansk/with-nn",
  DonetskGetAllNewsWithNNController.getAllSlovyanskNews
);
router.get(
  "/snishne/with-nn",
  DonetskGetAllNewsWithNNController.getAllSnishneNews
);
router.get(
  "/toretsk/with-nn",
  DonetskGetAllNewsWithNNController.getAllToretskNews
);
router.get(
  "/volnovaha/with-nn",
  DonetskGetAllNewsWithNNController.getAllVolnovakhaNews
);
router.get(
  "/yenakievo/with-nn",
  DonetskGetAllNewsWithNNController.getAllYenakievoNews
);

// Get News By Id Or Url
router.get(
  "/amvrosiivka/news/:param",
  DonetskGetNewsByIdOrUrlController.getAmvrosiivkaNewsByIdOrUrl
);
router.get(
  "/avdiyivka/news/:param",
  DonetskGetNewsByIdOrUrlController.getAvdiyivkaNewsByIdOrUrl
);
router.get(
  "/bahmut/news/:param",
  DonetskGetNewsByIdOrUrlController.getBahmutNewsByIdOrUrl
);
router.get(
  "/dobropilla/news/:param",
  DonetskGetNewsByIdOrUrlController.getDobropilliaNewsByIdOrUrl
);
router.get(
  "/dokuchaevsk/news/:param",
  DonetskGetNewsByIdOrUrlController.getDokuchaevskNewsByIdOrUrl
);
router.get(
  "/donetsk/news/:param",
  DonetskGetNewsByIdOrUrlController.getDonetskNewsByIdOrUrl
);
router.get(
  "/druzhkivka/news/:param",
  DonetskGetNewsByIdOrUrlController.getDrushkivkaNewsByIdOrUrl
);
router.get(
  "/gorlivka/news/:param",
  DonetskGetNewsByIdOrUrlController.getGorlivkaNewsByIdOrUrl
);
router.get(
  "/hartsyzk/news/:param",
  DonetskGetNewsByIdOrUrlController.getHartsyzskNewsByIdOrUrl
);
router.get(
  "/kostyantynivka/news/:param",
  DonetskGetNewsByIdOrUrlController.getKostyantynivkaNewsByIdOrUrl
);
router.get(
  "/kramatorsk/news/:param",
  DonetskGetNewsByIdOrUrlController.getKramatorskNewsByIdOrUrl
);
router.get(
  "/kurakhove/news/:param",
  DonetskGetNewsByIdOrUrlController.getKurakhoveNewsByIdOrUrl
);
router.get(
  "/liman/news/:param",
  DonetskGetNewsByIdOrUrlController.getLimanNewsByIdOrUrl
);
router.get(
  "/makiivka/news/:param",
  DonetskGetNewsByIdOrUrlController.getMakiivkaNewsByIdOrUrl
);
router.get(
  "/mariupol/news/:param",
  DonetskGetNewsByIdOrUrlController.getMariupolNewsByIdOrUrl
);
router.get(
  "/myrnograd/news/:param",
  DonetskGetNewsByIdOrUrlController.getMyrnohradNewsByIdOrUrl
);
router.get(
  "/pokrovsk/news/:param",
  DonetskGetNewsByIdOrUrlController.getPokrovskNewsByIdOrUrl
);
router.get(
  "/selidove/news/:param",
  DonetskGetNewsByIdOrUrlController.getSelidoveNewsByIdOrUrl
);
router.get(
  "/shakhtarsk/news/:param",
  DonetskGetNewsByIdOrUrlController.getShakhtarskNewsByIdOrUrl
);
router.get(
  "/slavyansk/news/:param",
  DonetskGetNewsByIdOrUrlController.getSlovyanskNewsByIdOrUrl
);
router.get(
  "/snishne/news/:param",
  DonetskGetNewsByIdOrUrlController.getSnishneNewsByIdOrUrl
);
router.get(
  "/toretsk/news/:param",
  DonetskGetNewsByIdOrUrlController.getToretskNewsByIdOrUrl
);
router.get(
  "/volnovaha/news/:param",
  DonetskGetNewsByIdOrUrlController.getVolnovakhaNewsByIdOrUrl
);
router.get(
  "/yenakievo/news/:param",
  DonetskGetNewsByIdOrUrlController.getYenakievoNewsByIdOrUrl
);

// Get All News By Date
router.get(
  "/amvrosiivka/news-today/:date",
  DonetskGetNewsByDateController.getAmvrosiivkaNewsByDate
);
router.get(
  "/avdiyivka/news-today/:date",
  DonetskGetNewsByDateController.getAvdiyivkaNewsByDate
);
router.get(
  "/bahmut/news-today/:date",
  DonetskGetNewsByDateController.getBahmutNewsByDate
);
router.get(
  "/dobropilla/news-today/:date",
  DonetskGetNewsByDateController.getDobropilliaNewsByDate
);
router.get(
  "/dokuchaevsk/news-today/:date",
  DonetskGetNewsByDateController.getDokuchaevskNewsByDate
);
router.get(
  "/donetsk/news-today/:date",
  DonetskGetNewsByDateController.getDonetskNewsByDate
);
router.get(
  "/druzhkivka/news-today/:date",
  DonetskGetNewsByDateController.getDrushkivkaNewsByDate
);
router.get(
  "/gorlivka/news-today/:date",
  DonetskGetNewsByDateController.getGorlivkaNewsByDate
);
router.get(
  "/hartsyzk/news-today/:date",
  DonetskGetNewsByDateController.getHartsyzskNewsByDate
);
router.get(
  "/kostyantynivka/news-today/:date",
  DonetskGetNewsByDateController.getKostyantynivkaNewsByDate
);
router.get(
  "/kramatorsk/news-today/:date",
  DonetskGetNewsByDateController.getKramatorskNewsByDate
);
router.get(
  "/kurakhove/news-today/:date",
  DonetskGetNewsByDateController.getKurakhoveNewsByDate
);
router.get(
  "/liman/news-today/:date",
  DonetskGetNewsByDateController.getLimanNewsByDate
);
router.get(
  "/makiivka/news-today/:date",
  DonetskGetNewsByDateController.getMakiivkaNewsByDate
);
router.get(
  "/mariupol/news-today/:date",
  DonetskGetNewsByDateController.getMariupolNewsByDate
);
router.get(
  "/myrnograd/news-today/:date",
  DonetskGetNewsByDateController.getMyrnohradNewsByDate
);
router.get(
  "/pokrovsk/news-today/:date",
  DonetskGetNewsByDateController.getPokrovskNewsByDate
);
router.get(
  "/selidove/news-today/:date",
  DonetskGetNewsByDateController.getSelidoveNewsByDate
);
router.get(
  "/shakhtarsk/news-today/:date",
  DonetskGetNewsByDateController.getShakhtarskNewsByDate
);
router.get(
  "/slavyansk/news-today/:date",
  DonetskGetNewsByDateController.getSlovyanskNewsByDate
);
router.get(
  "/snishne/news-today/:date",
  DonetskGetNewsByDateController.getSnishneNewsByDate
);
router.get(
  "/toretsk/news-today/:date",
  DonetskGetNewsByDateController.getToretskNewsByDate
);
router.get(
  "/volnovaha/news-today/:date",
  DonetskGetNewsByDateController.getVolnovakhaNewsByDate
);
router.get(
  "/yenakievo/news-today/:date",
  DonetskGetNewsByDateController.getYenakievoNewsByDate
);

// Update News
router.put(
  "/amvrosiivka/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateAmvrosiivkaNews
);
router.put(
  "/avdiyivka/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateAvdiyivkaNews
);
router.put(
  "/bahmut/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateBahmutNews
);
router.put(
  "/dobropilla/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateDobropilliaNews
);
router.put(
  "/dokuchaevsk/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateDokuchaevskNews
);
router.put(
  "/donetsk/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateDonetskNews
);
router.put(
  "/druzhkivka/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateDrushkivkaNews
);
router.put(
  "/gorlivka/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateGorlivkaNews
);
router.put(
  "/hartsyzk/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateHartsyzskNews
);
router.put(
  "/kostyantynivka/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateKostyantynivkaNews
);
router.put(
  "/kramatorsk/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateKramatorskNews
);
router.put(
  "/kurakhove/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateKurakhoveNews
);
router.put(
  "/liman/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateLimanNews
);
router.put(
  "/makiivka/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateMakiivkaNews
);
router.put(
  "/mariupol/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateMariupolNews
);
router.put(
  "/myrnograd/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateMyrnohradNews
);
router.put(
  "/pokrovsk/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updatePokrovskNews
);
router.put(
  "/selidove/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateSelidoveNews
);
router.put(
  "/shakhtarsk/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateShakhtarskNews
);
router.put(
  "/slavyansk/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateSlovyanskNews
);
router.put(
  "/snishne/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateSnishneNews
);
router.put(
  "/toretsk/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateToretskNews
);
router.put(
  "/volnovaha/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateVolnovakhaNews
);
router.put(
  "/yenakievo/news/edit/:id",
  checkAuth,
  DonetskUpdateNewsController.updateYenakievoNews
);

// Delete News
router.post(
  "/amvrosiivka/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteAmvrosiivkaNews
);
router.post(
  "/avdiyivka/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteAvdiyivkaNews
);
router.post(
  "/bahmut/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteBahmutNews
);
router.post(
  "/dobropilla/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteDobropilliaNews
);
router.post(
  "/dokuchaevsk/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteDokuchaevskNews
);
router.post(
  "/donetsk/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteDonetskNews
);
router.post(
  "/druzhkivka/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteDrushkivkaNews
);
router.post(
  "/gorlivka/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteGorlivkaNews
);
router.post(
  "/hartsyzk/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteHartsyzskNews
);
router.post(
  "/kostyantynivka/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteKostyantynivkaNews
);
router.post(
  "/kramatorsk/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteKramatorskNews
);
router.post(
  "/kurakhove/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteKurakhoveNews
);
router.post(
  "/liman/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteLimanNews
);
router.post(
  "/makiivka/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteMakiivkaNews
);
router.post(
  "/mariupol/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteMariupolNews
);
router.post(
  "/myrnograd/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteMyrnohradNews
);
router.post(
  "/pokrovsk/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deletePokrovskNews
);
router.post(
  "/selidove/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteSelidoveNews
);
router.post(
  "/shakhtarsk/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteShakhtarskNews
);
router.post(
  "/slavyansk/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteSlovyanskNews
);
router.post(
  "/snishne/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteSnishneNews
);
router.post(
  "/toretsk/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteToretskNews
);
router.post(
  "/volnovaha/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteVolnovakhaNews
);
router.post(
  "/yenakievo/news/delete/:id",
  checkAuth,
  DonetskDeleteNewsController.deleteYenakievoNews
);

// Search News
router.get(
  "/amvrosiivka/search",
  DonetskSearchNewsController.searchAmvrosiivkaNews
);
router.get(
  "/avdiyivka/search",
  DonetskSearchNewsController.searchAvdiyivkaNews
);
router.get("/bahmut/search", DonetskSearchNewsController.searchBahmutNews);
router.get(
  "/dobropilla/search",
  DonetskSearchNewsController.searchDobropilliaNews
);
router.get(
  "/dokuchaevsk/search",
  DonetskSearchNewsController.searchDokuchaevskNews
);
router.get("/donetsk/search", DonetskSearchNewsController.searchDonetskNews);
router.get(
  "/druzhkivka/search",
  DonetskSearchNewsController.searchDrushkivkaNews
);
router.get("/gorlivka/search", DonetskSearchNewsController.searchGorlivkaNews);
router.get("/hartsyzk/search", DonetskSearchNewsController.searchHartsyzskNews);
router.get(
  "/kostyantynivka/search",
  DonetskSearchNewsController.searchKostyantynivkaNews
);
router.get(
  "/kramatorsk/search",
  DonetskSearchNewsController.searchKramatorskNews
);
router.get(
  "/kurakhove/search",
  DonetskSearchNewsController.searchKurakhoveNews
);
router.get("/liman/search", DonetskSearchNewsController.searchLimanNews);
router.get("/makiivka/search", DonetskSearchNewsController.searchMakiivkaNews);
router.get("/mariupol/search", DonetskSearchNewsController.searchMariupolNews);
router.get(
  "/myrnograd/search",
  DonetskSearchNewsController.searchMyrnohradNews
);
router.get("/pokrovsk/search", DonetskSearchNewsController.searchPokrovskNews);
router.get("/selidove/search", DonetskSearchNewsController.searchSelidoveNews);
router.get(
  "/shakhtarsk/search",
  DonetskSearchNewsController.searchShakhtarskNews
);
router.get(
  "/slavyansk/search",
  DonetskSearchNewsController.searchSlovyanskNews
);
router.get("/snishne/search", DonetskSearchNewsController.searchSnishneNews);
router.get("/toretsk/search", DonetskSearchNewsController.searchToretskNews);
router.get(
  "/volnovaha/search",
  DonetskSearchNewsController.searchVolnovakhaNews
);
router.get(
  "/yenakievo/search",
  DonetskSearchNewsController.searchYenakievoNews
);

export default router;
