import NewsModel from "../../../utils/news/newsModel.js";

export const Severodonetsk = NewsModel("severodonetsks");
export const Lysychansk = NewsModel("lysychansks");
export const Rubizhne = NewsModel("rubizhnes");
export const Pervomaisk93200 = NewsModel("93200_pervomaisks");
export const Luhansk = NewsModel("luhansks");
export const Hrustalnyi = NewsModel("hrustalnyis");
export const Alchevsk = NewsModel("alchevsks");
export const Kadievka = NewsModel("kadievkas");
export const Dovzhansk = NewsModel("dovzhansks");
export const Antracit = NewsModel("antracits");
export const Brianka = NewsModel("briankas");
export const Rivenky = NewsModel("rivenkys");
export const Sorokyne = NewsModel("sorokynes");
export const Golubivka = NewsModel("golubivkas");
export const Perevalsk = NewsModel("perevalsk");
export const Popasna = NewsModel("popasnas");
export const Molodohvardiisk = NewsModel("molodohvardiisks");
export const Kreminna = NewsModel("kreminnas");
export const Suhodilsk = NewsModel("suhodilsks");
